[project]
name = "requete-pipelines"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pyspark==3.5.0",
    "duckdb>=1.1.0",
    "requete>=0.1.0",
]

[tool.basedpyright]
pythonVersion = "3.11"
venvPath = "."
venv = ".venv"
